###

# Get all Todos

GET http://127.0.0.1:8000/api/todos  HTTP/1.1
Content-Type: application/json
Accept: application/json



###

# Create a Todo

POST http://127.0.0.1:8000/api/todos  HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 

{
"task": "Paint the house",
"status": 0
}



###

# Get a Todo

GET http://127.0.0.1:8000/api/todos/6  HTTP/1.1
content-type: application/json
Accept: application/json



###

# Update a Todo

PUT http://127.0.0.1:8000/api/todos/2  HTTP/1.1
content-type: application/json
Accept: application/json

{
    "task": "Update4",
    "status": 1
}
    


###
# Delete a Todo

DELETE http://127.0.0.1:8000/api/todos/1  HTTP/1.1
content-type: application/json
Accept: application/json



###
# Search for Todo(s) with a name

# Returns an array

GET http://127.0.0.1:8000/api/todos/search/m  HTTP/1.1
content-type: application/json
Accept: application/json



###

# New User Registration

POST http://127.0.0.1:8000/api/register  HTTP/1.1
content-type: application/json
Accept: application/json

{
    "name": "Prof Dev",
    "email": "prof@gmail.com",
    "password": "prof1000",
    "password_confirmation": "prof1000"
}


###

# User Login

POST http://127.0.0.1:8000/api/login  HTTP/1.1
Content-Type: application/json
Accept: application/json

{
"email": "prof2@gmail.com",
"password": "prof2000"
}



###

# User LogOut

POST http://127.0.0.1:8000/api/logout  HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 3|RnM12vt66Num2ky54COx5s7TihbJdlCw7H6sFz3p





###
# Token Bank
#id-1
# Bearer 4|MTPMBONxki6S8h7vy0CBt7mS9DkAJOwbNfSgAuUk
#id-2
# Bearer 5|2lcsTxGldljPOWkS7ZDjhtuhR30m1ANHBZPfIGWg
#id-4
# Bearer 6|lIcFZpQxcOhDFflKs0MalwRwP0nIOXlPXvNa5ALw  xxxxxx
#id-6
# 8|vQvLJqNB9ighNniRih2tDI9FXeaL6r9EvypXtYX0 xxxxxxxx
#id-8
# 10|Mcm2YuvJ1Yfcaw3rJiqGccvnfF4tCKe3Jh6GGfpQ xxxxx
#id-9
# 11|FeVPbvIi6HKitipzM23bXL4BoV2GAvWjIeVSRjwo xxxxxxx
#id-10
# 12|cTe9JxA3HnOyUsLfBVQZkd9nTJhWoYnyJB2QWH5w
#id-11
# 13|JgOdrIhMWTL3REBdKnREZ1EbSfUlEggLFAKLjd1G
#id-12
# 14|382Qv2FrspVyY0sUDDWTtivaC2dnq2PMhpdCnVyq xxxxxx
#id-5
# 15|Rw3V6AfluD0PFtvY5cbYvBd1TnyzS95QWm2FA9wb xxxxxxx
# 17|rFuhKYiD9Z1F6hsoBNbomZSwL2EIaC9aT44jWB6T